server:
  port: 9003

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
      url: jdbc:mysql://localhost:3306/database1?useSSL=false
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver